# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\"3\n\x08Resource\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"-\n\x0eGetAllResponse\x12\x1b\n\x08resource\x18\x01 \x01(\x0b\x32\t.Resource\"\x1c\n\x0eGetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0fGetByIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2]\n\nAggregator\x12#\n\x06GetAll\x12\x06.Empty\x1a\x0f.GetAllResponse\"\x00\x12*\n\x03Get\x12\x0f.GetByIdRequest\x1a\x10.GetByIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCE']._serialized_start=20
  _globals['_RESOURCE']._serialized_end=71
  _globals['_EMPTY']._serialized_start=73
  _globals['_EMPTY']._serialized_end=80
  _globals['_GETALLRESPONSE']._serialized_start=82
  _globals['_GETALLRESPONSE']._serialized_end=127
  _globals['_GETBYIDREQUEST']._serialized_start=129
  _globals['_GETBYIDREQUEST']._serialized_end=157
  _globals['_GETBYIDRESPONSE']._serialized_start=159
  _globals['_GETBYIDRESPONSE']._serialized_end=205
  _globals['_AGGREGATOR']._serialized_start=207
  _globals['_AGGREGATOR']._serialized_end=300
# @@protoc_insertion_point(module_scope)
