version: "3.8"

services:
  gateway:
    container_name: "api-gateway"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 3005:3005

  events:
    container_name: "api-aggregator"
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  venues:
    container_name: "api-publisher"
    build:
      context: ./publisher
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
  client:
    container_name: "app-client"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # users:
  #   container_name: "api-users"
  # venues:
  #   container_name: "api-venues"
  # client:
  #   container_name: "app-client"
