# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rss.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trss.proto\":\n\x08NewsItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\")\n\x0eGetAllResponse\x12\x17\n\x04item\x18\x01 \x01(\x0b\x32\t.NewsItem\"\x1c\n\x0eGetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x0fGetByIdResponse\x12\x17\n\x04item\x18\x01 \x01(\x0b\x32\t.NewsItem2`\n\rRSSAggregator\x12#\n\x06GetAll\x12\x06.Empty\x1a\x0f.GetAllResponse\"\x00\x12*\n\x03Get\x12\x0f.GetByIdRequest\x1a\x10.GetByIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWSITEM']._serialized_start=13
  _globals['_NEWSITEM']._serialized_end=71
  _globals['_EMPTY']._serialized_start=73
  _globals['_EMPTY']._serialized_end=80
  _globals['_GETALLRESPONSE']._serialized_start=82
  _globals['_GETALLRESPONSE']._serialized_end=123
  _globals['_GETBYIDREQUEST']._serialized_start=125
  _globals['_GETBYIDREQUEST']._serialized_end=153
  _globals['_GETBYIDRESPONSE']._serialized_start=155
  _globals['_GETBYIDRESPONSE']._serialized_end=197
  _globals['_RSSAGGREGATOR']._serialized_start=199
  _globals['_RSSAGGREGATOR']._serialized_end=295
# @@protoc_insertion_point(module_scope)
