# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpublisher.proto\" \n\x11\x43reateFeedRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\".\n\x12\x43reateFeedResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66\x65\x65\x64\x18\x02 \x01(\t2D\n\tPublisher\x12\x37\n\nCreateFeed\x12\x12.CreateFeedRequest\x1a\x13.CreateFeedResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publisher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEFEEDREQUEST']._serialized_start=19
  _globals['_CREATEFEEDREQUEST']._serialized_end=51
  _globals['_CREATEFEEDRESPONSE']._serialized_start=53
  _globals['_CREATEFEEDRESPONSE']._serialized_end=99
  _globals['_PUBLISHER']._serialized_start=101
  _globals['_PUBLISHER']._serialized_end=169
# @@protoc_insertion_point(module_scope)
